services:
  - type: web
    name: event-storage-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CORS_ORIGIN
        value: https://hookedirl.com,https://www.hookedirl.com,https://leventeirikikss.github.io
